MaisSfdx/force-app/main/default/objects/Candidato__c/Candidato__c.object-meta.xml
<CustomObject>
    <description>Um candidato é uma pessoa que foi convidada para participar dos jogos mas ainda não aceitou.</description>
    <label>Candidato</label>
    <nameField>
        <label>Nome do candidato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MaisSfdx/force-app/main/default/objects/Candidato__c/fields/Aceite__c.field-meta.xml
<CustomField>
    <fullName>Aceite__c</fullName>
    <defaultValue>false</defaultValue>
    <description>usado para informar se o candidato aceitou o desafio.</description>
    <inlineHelpText>usado para informar se o candidato aceitou o desafio.</inlineHelpText>
    <label>Aceite</label>
    <type>Checkbox</type>
</CustomField>

MaisSfdx/force-app/main/default/classes/CandidatoTriggerHandler.cls
public with sharing class CandidatoTriggerHandler {
    public CandidatoTriggerHandler() {
        
    }

    public static void beforeUpdate(List<Candidato__c> records, Map<Id, Candidato__c> oldMap) {
        for (Candidato__c candidato : records) {             
            if(candidato.Aceite__c == true){                
               candidato.addError('Candidato com aceite não pode ser alterado.');                
            }
        }
    }
}