salesfoceround/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participantes do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesfoceround/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>usado para informar se o jogador foi eliminado.</description>
    <inlineHelpText>Jogador Eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

salesfoceround/force-app/main/default/classes/JogadoresTriggerHandler.cls
public with sharing class JogadoresTriggerHandler {
    public static void beforeUpdate (List<Jogador__c> records, Map<Id, Jogador__c> oldMap){
        for (Jogador__c jogador : records){
            Jogador__c jogadorOld = oldmap.get(jogador.Id);

            if(!jogadorOld.Eliminado__c && jogador.Eliminado__c){
                jogador.DaraMorte__c = System.now(); 
            }
        }

    }
}