salesfoceround/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participantes do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesfoceround/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>usado para informar se o jogador foi eliminado.</description>
    <inlineHelpText>Jogador Eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

salesfoceround/force-app/main/default/objects/ParticipantesPartida__c/ParticipantesPartida__c.object-meta.xml
<CustomObject>
    <description>tabela de ligação entre jogador e partida</description>
    <label>Participantes da Partida</label>
    <nameField>
        <displayFormat>Par-{00000}</displayFormat>
        <label>Número de Participantes da Partida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes das Partidas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesfoceround/force-app/main/default/objects/ParticipantesPartida__c/fields/Jogador__c.field-meta.xml
<CustomField>
    <fullName>Jogador__c</fullName>
    <description>Jogador da Partida</description>
    <inlineHelpText>Jogador da Partida</inlineHelpText>
    <label>Jogador</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Participantes das Partidas</relationshipLabel>
    <relationshipName>ParticipantesdaPartida</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MaisSfdx/force-app/main/default/objects/ParticipantesPartida__c/fields/Partida__c.field-meta.xml
<CustomField>
    <fullName>Partida__c</fullName>
    <description>partida</description>
    <inlineHelpText>partida</inlineHelpText>
    <label>Partida</label>
    <referenceTo>Partida__c</referenceTo>
    <relationshipLabel>Participantes das Partidas</relationshipLabel>
    <relationshipName>ParticipantesdaPartida</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MaisSfdx/force-app/main/default/objects/Partida__c/Partida__c.object-meta.xml
<CustomObject>
    <label>Partida</label>
    <nameField>
        <label>Nome de pARTIDA</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partidas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesfoceround/force-app/main/default/objects/Partida__c/fields/TerminoPartida__c.field-meta.xml
<CustomField>
    <fullName>TerminoPartida__c</fullName>
    <description>TerminoPartida</description>
    <inlineHelpText>TerminoPartida</inlineHelpText>
    <label>Término da partida</label>
    <type>DateTime</type>
</CustomField>

salesfoceround/force-app/main/default/classes/BatatinhaFrita.cls
public class BatatinhaFrita implements IPartida{

    public void execute (Id idPartida){
        
    	ParticipantesPartida__c[]  participantes = [SELECT Id, Jogador__c FROM ParticipantesPartida__c where Partida__c = :idPartida ];
        
        Jogador__c[] jogadores = new List<Jogador__c>();
        
        Integer mortes = (Integer) participantes.size() / 2; 
        
        for(Integer i = 0; i < mortes; i++){
            Jogador__c jogador = new Jogador__c();
            jogador.Id = participantes[i].Jogador__c;
            jogador.Eliminado__c = true;
            jogadores.add(jogador); 
        }
        
        System.debug(jogadores); 
        
        update jogadores;
        
        update new Partida__c(Id = idPartida, TerminoPartida__c = System.now());  
        
    }    
    
}