MaisSfdx/force-app/main/default/objects/Assassinato__c/Assassinato__c.object-meta.xml
<CustomObject>
    <label>Assassinato</label>
    <nameField>
        <displayFormat>Ass-{0000}</displayFormat>
        <label>Nome de Assassinato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assassinatos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MaisSfdx/force-app/main/default/objects/Assassinato__c/fields/Assassinado__c.field-meta.xml
<CustomField>
    <fullName>Assassinado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Assassinado</description>
    <inlineHelpText>Assassinado</inlineHelpText>
    <label>Assassinado</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Assassinatos (Assassinado)</relationshipLabel>
    <relationshipName>Assassinatos</relationshipName>
    <type>Lookup</type>
</CustomField>

salesfoceround/force-app/main/default/objects/Assassinato__c/fields/Assassino__c.field-meta.xml
<CustomField>
    <fullName>Assassino__c</fullName>
    <description>Assassino</description>
    <inlineHelpText>Assassino</inlineHelpText>
    <label>Assassino</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Assassinatos</relationshipLabel>
    <relationshipName>Assassinos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MaisSfdx/force-app/main/default/objects/Assassinato__c/fields/DataHora__c.field-meta.xml
<CustomField>
    <fullName>DataHora__c</fullName>
    <label>Data e hora</label>
    <type>DateTime</type>
</CustomField>

salesfoceround/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participantes do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesfoceround/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>usado para informar se o jogador foi eliminado.</description>
    <inlineHelpText>Jogador Eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

MaisSfdx/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MaisSfdx/force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>USado para representar p jogo da serie Round 6 .</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

salesfoceround/force-app/main/default/objects/Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Definição</fullName>
                <default>true</default>
                <label>Em Definição</label>
            </value>
            <value>
                <fullName>Coletando Candidatos</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesfoceround/force-app/main/default/classes/AssassinatosHandler.cls
public with sharing class AssassinatosHandler {

    static FINAL Integer INICIO_DADO = 1;
    static FINAL Integer DEU_CHANCE_CONTRA_GOLPE = 1;
    static FINAL Integer NUMERO_LADOS_D20 = 20;
    static FINAL Integer NUMERO_LADOS_D10 = 10;

    public AssassinatosHandler() {

    }

    
    public static void execute(){

        List<Jogador__c> jogadoresRound = new List<Jogador__c>(selectJogadorByRound());
        
        combate(jogadoresRound);

        update jogadoresRound;  // tentar testar no developer console. // Aqui já vai chamar a trigger
                                    //  Então vai mexer no objeto mesmo.          
    }

    @TestVisible
    static void combate (List<Jogador__c> jogadoresRound){

        Jogador__c atacante  = determinaJogador(jogadoresRound,null);
        System.debug('Jogador atacante' + atacante);
        
        Jogador__c defensor = determinaJogador(jogadoresRound,atacante); 
		System.debug('Jogador defensor' + defensor);
        
        Integer dadoAssassino = jogarDados(NUMERO_LADOS_D20,INICIO_DADO); 
        System.debug('Dados do Assassino ' + dadoAssassino);
        Integer jogadaAssassino =  dadoAssassino + Integer.valueOf(atacante.Forca__c);
        System.debug('Jogada do Assassino ' + jogadaAssassino);
        Integer defesaAssassinado = defender(defensor);
        System.debug('Jogada do Defensor ' + defesaAssassinado);
      
        if(jogadaAssassino > defesaAssassinado){
            defensor.Morreu__c = true;
            setarDadoAssassinoAssassinado(atacante,defensor);             
        }else{
            if(DEU_CHANCE_CONTRA_GOLPE == dadoAssassino){
                System.debug('Houve contra golpe'); 
                Integer novoAtacanteJoga = jogarDados(NUMERO_LADOS_D20,INICIO_DADO) + Integer.valueOf(defensor.Forca__c); 
                System.debug('Contra Golpe do Novo Atacante...' + novoAtacanteJoga); 
                Integer defesaContraGolpe = defender(atacante);
                System.debug('Defesa do outrora atacante...' + defesaContraGolpe);

                if (novoAtacanteJoga > defesaContraGolpe){
                    atacante.Morreu__c = true; 
                    setarDadoAssassinoAssassinado(defensor,atacante);                      
                }

            }       
        }

    }
    static Jogador__c determinaJogador(List<Jogador__c> jogadoresRound, Jogador__c jogador){
        //Garantir que não serão iguais.
        Jogador__c jogadorAleatorio = jogadoresRound.get(Utils.generateRandomIntegerBetween(jogadoresRound.size()-1,0));
        if(null != jogador){
            while (jogadorAleatorio.Id == jogador.Id){
                jogadorAleatorio = jogadoresRound.get(Utils.generateRandomIntegerBetween(jogadoresRound.size()-1,0));
            }
        }
        return jogadorAleatorio;
    }

    static void setarDadoAssassinoAssassinado(Jogador__c jogadorAssassino,Jogador__c jogadorAssassinado){
        Assassinato__c assassinato = new Assassinato__c (); 
        assassinato.Assassino__c = jogadorAssassino.Id;
        assassinato.Assassinado__c = jogadorAssassinado.Id; 
        assassinato.DataHora__c = System.now();
        insert assassinato;
    }

    static Integer jogarDados(Integer inicio, Integer lados){
        return Utils.generateRandomIntegerBetween(inicio, lados);
    }

    static Integer defender(Jogador__c jogadorDefende){
        return 
            (
              jogarDados(NUMERO_LADOS_D10,INICIO_DADO) + 
              jogarDados(NUMERO_LADOS_D10,INICIO_DADO) + 
              Integer.valueOf(jogadorDefende.Inteligencia__c) + 
              Integer.valueOf(jogadorDefende.Velocidade__c)
            );  
    }

    static List<Jogador__c> selectJogadorByRound() { //voltar para saber o que eu pego aqui
        return [
            SELECT Id, Name, Nick__c, Forca__c, Round__r.Status__C, Inteligencia__c, Velocidade__c,
                   Eliminado__c
                FROM Jogador__c
              WHERE Round__r.Status__c = 'Em andamento' AND Eliminado__c = false                
        ];
    }
}