MaisSfdx/force-app/main/default/objects/Piloto__c/Piloto__c.object-meta.xml
<CustomObject>
    <description>Pilotos de Fórmula 1</description>
    <label>Piloto</label>
    <nameField>
        <label>Nome de Piloto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pilotos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MaisSfdx/force-app/main/default/objects/Piloto__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>O piloto está no campeonato.</description>
    <inlineHelpText>O piloto está no campeonato.</inlineHelpText>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

MaisSfdx/force-app/main/default/classes/PilotosTriggerHandler.cls
public with sharing class PilotosTriggerHandler {
    public PilotosTriggerHandler() {

    }   

    public static void beforeUpdate(List<Piloto__c> records, Map<Id, Piloto__c> oldMap) {
        for (Piloto__c piloto : records) {             
            if(!piloto.Ativo__c){                
               piloto.addError('O Piloto que não está ativo não pode ser alterado.');                
            }
        }
    }
}